site_name: HTMA
nav:
  - Home: index.md
  - ImageCompression: imageCompression.md
  - Parametric Cad: parametric.md
  - Laser Cutting: lasers.md
  - 3D Printing: 3Dprinting.md

theme: 
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  analytics:
    gtag: G-YT7Z6VQ5M4 