site_name: HTMA
nav:
  - Home: index.md
  - ImageCompression: imageCompression.md
  #- Parametric Design: parametric.md
  - Laser Cutting: lasers.md
  - Vinyl Cutting: vinyl.md
  #- 3D Printing: 3Dprinting.md
  - Machine/Software Tutorials:
      - Makera Z1 PCBs: makera.md
      - PrusaSlicer: prusaSlicer.md
      #- Xtool F1 Ultra: F1Ultra.md
      #- Laser PCBs: laserPCBs.md
      #- KiCad PCB design: Kicad.md


theme: 
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  analytics:
    gtag: G-YT7Z6VQ5M4 